# docker-compose.yml
services:
  ollama:
    image: ollama/ollama
    container_name: erp-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

  erp-agent:
    build: .
    container_name: erp-agent-v3
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - API_URL=http://erp-agent:8000/chat/
    depends_on:
      - ollama

volumes:
  ollama_data: