services:
  ollama:
    image: ollama/ollama
    container_name: erp-ollama
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama
    command: serve
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

  erp-agent:
    build: .
    container_name: erp-agent-v3
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_API_BASE=http://erp-ollama:11434
    depends_on:
      - ollama
volumes:
  ollama:


#services:
#  ollama:
#    image: ollama/ollama
#    container_name: erp-ollama
#    ports:
#      - "11434:11434"
#    volumes:
#      - ~/.ollama:/root/.ollama  # Use host's Ollama directory
#    command: serve
##    volumes:
##      - ollama_data:/root/.ollama
##    # Remove the pull command from here - do it separately
##    command: serve
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:11434"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  erp-agent:
#    build: .
#    container_name: erp-agent-v3
#    ports:
#      - "8000:8000"
#      - "8501:8501"
#    volumes:
#      - .:/app
#    environment:
#      - PYTHONUNBUFFERED=1
##      - OLLAMA_API_BASE=http://erp-ollama:11434
#    depends_on:
#      - ollama
#    # Add healthcheck and better startup handling
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#
#volumes:
#  ollama_data: